In [2]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [3]:
data = pd.read_csv('Steeldata.csv')
data

Unnamed: 0 Country  Year                  Category              State  \
0              0   India  2021  Non-Alloy Finished Steel  Jammu and Kashmir   
1              1   India  2020  Non-Alloy Finished Steel  Jammu and Kashmir   
2              2   India  2021  Non-Alloy Finished Steel     Andhra Pradesh   
3              3   India  2021  Non-Alloy Finished Steel     Andhra Pradesh   
4              4   India  2020  Non-Alloy Finished Steel     Andhra Pradesh   
...          ...     ...   ...                       ...                ...   
996          996   India  2021  Non-Alloy Finished Steel  Jammu and Kashmir   
997          997   India  2021  Non-Alloy Finished Steel        Maharashtra   
998          998   India  2021  Non-Alloy Finished Steel              Delhi   
999          999   India  2021  Non-Alloy Finished Steel   Himachal Pradesh   
1000        1000   India  2019  Non-Alloy Finished Steel     Andhra Pradesh   

                      Type  Consumption  
0            Bars and Rods      5.71420  
1          Stainless Steel      5.16517  
2          Stainless Steel     45.71400  
3                  HR Coil     43.56800  
4            Bars and Rods     45.71400  
...                    ...          ...  
996        Stainless Steel     45.28570  
997        Stainless Steel     40.28570  
998   Galvanized Iron Coil     46.49985  
999                HR Coil     39.64270  
1000  Galvanized Iron Coil     56.33050  

[1001 rows x 7 columns]

In [4]:
data.head()

Unnamed: 0 Country  Year                  Category              State  \
0           0   India  2021  Non-Alloy Finished Steel  Jammu and Kashmir   
1           1   India  2020  Non-Alloy Finished Steel  Jammu and Kashmir   
2           2   India  2021  Non-Alloy Finished Steel     Andhra Pradesh   
3           3   India  2021  Non-Alloy Finished Steel     Andhra Pradesh   
4           4   India  2020  Non-Alloy Finished Steel     Andhra Pradesh   

              Type  Consumption  
0    Bars and Rods      5.71420  
1  Stainless Steel      5.16517  
2  Stainless Steel     45.71400  
3          HR Coil     43.56800  
4    Bars and Rods     45.71400

In [5]:
for i in range(len(data["Country"])):
  data["Country"][i] = 0

C:\Users\NARESH KUMAR SAW\AppData\Local\Temp\ipykernel_11276\697309281.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data["Country"][i] = 0


In [6]:
print(data)

      Unnamed: 0 Country  Year                  Category              State  \
0              0       0  2021  Non-Alloy Finished Steel  Jammu and Kashmir   
1              1       0  2020  Non-Alloy Finished Steel  Jammu and Kashmir   
2              2       0  2021  Non-Alloy Finished Steel     Andhra Pradesh   
3              3       0  2021  Non-Alloy Finished Steel     Andhra Pradesh   
4              4       0  2020  Non-Alloy Finished Steel     Andhra Pradesh   
...          ...     ...   ...                       ...                ...   
996          996       0  2021  Non-Alloy Finished Steel  Jammu and Kashmir   
997          997       0  2021  Non-Alloy Finished Steel        Maharashtra   
998          998       0  2021  Non-Alloy Finished Steel              Delhi   
999          999       0  2021  Non-Alloy Finished Steel   Himachal Pradesh   
1000        1000       0  2019  Non-Alloy Finished Steel     Andhra Pradesh   

                      Type  Consumption  
0        

In [7]:
for i in range(len(data["Category"])):
  data["Category"][i] = 0

C:\Users\NARESH KUMAR SAW\AppData\Local\Temp\ipykernel_11276\415511639.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data["Category"][i] = 0


In [8]:
print(data['Type'].unique())
GI, HR, SS, BR = 'Galvanized Iron Coil', 'HR Coil', 'Stainless Steel', 'Bars and Rods'
for i in range(len(data["Type"])):
    if data['Type'][i] == GI:
      data["Type"][i] = 1
    if data['Type'][i] == HR:
      data["Type"][i] = 2
    if data['Type'][i] == SS:
      data["Type"][i] = 3
    if data['Type'][i] == BR:
      data["Type"][i] = 4

['Bars and Rods' 'Stainless Steel' 'HR Coil' 'Galvanized Iron Coil']


C:\Users\NARESH KUMAR SAW\AppData\Local\Temp\ipykernel_11276\3844060632.py:11: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data["Type"][i] = 4
C:\Users\NARESH KUMAR SAW\AppData\Local\Temp\ipykernel_11276\3844060632.py:9: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data["Type"][i] = 3
C:\Users\NARESH KUMAR SAW\AppData\Local\Temp\ipykernel_11276\3844060632.py:7: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data["Type"][i] = 2
C:\Use

In [9]:
data

Unnamed: 0 Country  Year Category              State Type  Consumption
0              0       0  2021        0  Jammu and Kashmir    4      5.71420
1              1       0  2020        0  Jammu and Kashmir    3      5.16517
2              2       0  2021        0     Andhra Pradesh    3     45.71400
3              3       0  2021        0     Andhra Pradesh    2     43.56800
4              4       0  2020        0     Andhra Pradesh    4     45.71400
...          ...     ...   ...      ...                ...  ...          ...
996          996       0  2021        0  Jammu and Kashmir    3     45.28570
997          997       0  2021        0        Maharashtra    3     40.28570
998          998       0  2021        0              Delhi    1     46.49985
999          999       0  2021        0   Himachal Pradesh    2     39.64270
1000        1000       0  2019        0     Andhra Pradesh    1     56.33050

[1001 rows x 7 columns]

In [10]:
ff= data['State'].unique()
m = {i:0 for i in ff}
c = 10 
for i in ff:
  m[i]+=c
  c+=1
print(m)

{'Jammu and Kashmir': 10, 'Andhra Pradesh': 11, 'Arunachal Pradesh': 12, 'Assam': 13, 'Bihar': 14, 'Chhattisgarh': 15, 'Goa': 16, 'Gujarat': 17, 'Haryana': 18, 'Himachal Pradesh': 19, 'Jharkhand': 20, 'Karnataka': 21, 'Kerala': 22, 'Madhya Pradesh': 23, 'Maharashtra': 24, 'Manipur': 25, 'Meghalaya': 26, 'Mizoram': 27, 'Nagaland': 28, 'Odisha': 29, 'Punjab': 30, 'Rajasthan': 31, 'Sikkim': 32, 'Tamil Nadu': 33, 'Telangana': 34, 'Tripura': 35, 'Uttar Pradesh': 36, 'Uttarakhand': 37, 'West Bengal': 38, 'Chandigarh': 39, 'Delhi': 40}


In [11]:
kk  = []
for i in range(len(data["State"])):
  data['State'][i] = m[data["State"][i]]
data

C:\Users\NARESH KUMAR SAW\AppData\Local\Temp\ipykernel_11276\2822113246.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['State'][i] = m[data["State"][i]]


Unnamed: 0 Country  Year Category State Type  Consumption
0              0       0  2021        0    10    4      5.71420
1              1       0  2020        0    10    3      5.16517
2              2       0  2021        0    11    3     45.71400
3              3       0  2021        0    11    2     43.56800
4              4       0  2020        0    11    4     45.71400
...          ...     ...   ...      ...   ...  ...          ...
996          996       0  2021        0    10    3     45.28570
997          997       0  2021        0    24    3     40.28570
998          998       0  2021        0    40    1     46.49985
999          999       0  2021        0    19    2     39.64270
1000        1000       0  2019        0    11    1     56.33050

[1001 rows x 7 columns]

In [12]:
for i in range(len(data["Consumption"])):
  data["Consumption"][i] = round(data["Consumption"][i])

C:\Users\NARESH KUMAR SAW\AppData\Local\Temp\ipykernel_11276\3982889767.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data["Consumption"][i] = round(data["Consumption"][i])


In [13]:
data

Unnamed: 0 Country  Year Category State Type  Consumption
0              0       0  2021        0    10    4          6.0
1              1       0  2020        0    10    3          5.0
2              2       0  2021        0    11    3         46.0
3              3       0  2021        0    11    2         44.0
4              4       0  2020        0    11    4         46.0
...          ...     ...   ...      ...   ...  ...          ...
996          996       0  2021        0    10    3         45.0
997          997       0  2021        0    24    3         40.0
998          998       0  2021        0    40    1         46.0
999          999       0  2021        0    19    2         40.0
1000        1000       0  2019        0    11    1         56.0

[1001 rows x 7 columns]

In [14]:
print(data['Consumption'].unique())

[ 6.  5. 46. 44. 17. 12. 15. 47. 22. 23. 20. 14. 51. 52. 29. 41. 40. 54.
 43. 11. 37. 39. 66. 71. 73.  3.  0.  7. 21. 63. 61. 64. 69. 70. 67. 26.
 32. 24. 25. 33. 28. 19. 50. 18. 49. 30. 56. 16. 45. 36. 57. 53. 27.  2.
 60. 31.  8. 38. 42.  9. 55. 34. 59. 58. 72. 13. 35. 10. 62. 48.  4.]


In [15]:
data.drop('Country', axis=1, inplace=True)
data.drop('Category', axis=1, inplace=True)
data

Unnamed: 0  Year State Type  Consumption
0              0  2021    10    4          6.0
1              1  2020    10    3          5.0
2              2  2021    11    3         46.0
3              3  2021    11    2         44.0
4              4  2020    11    4         46.0
...          ...   ...   ...  ...          ...
996          996  2021    10    3         45.0
997          997  2021    24    3         40.0
998          998  2021    40    1         46.0
999          999  2021    19    2         40.0
1000        1000  2019    11    1         56.0

[1001 rows x 5 columns]

In [16]:
q1  = sum(data["Consumption"][0:14])/14
q2 = sum(data["Consumption"][14:28])/14     
q3 = sum(data["Consumption"][28:42])/14
q4 = sum(data["Consumption"][42:56])/14
q5 = sum(data["Consumption"][42:56])/14
for i in range(len(data["Consumption"])):
  if i<200:
    data["Consumption"][i] = 1
  if i<400 and i>200:
    data["Consumption"][i] = 2
  if i<600 and i>400:
    data["Consumption"][i] = 3
  if i<800 and i>600:
    data["Consumption"][i] = 4
  if i<=1000 and i>800:
    data["Consumption"][i] = 5

C:\Users\NARESH KUMAR SAW\AppData\Local\Temp\ipykernel_11276\150824385.py:8: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data["Consumption"][i] = 1
C:\Users\NARESH KUMAR SAW\AppData\Local\Temp\ipykernel_11276\150824385.py:10: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data["Consumption"][i] = 2
C:\Users\NARESH KUMAR SAW\AppData\Local\Temp\ipykernel_11276\150824385.py:12: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data["Consumpt

In [17]:
data

Unnamed: 0  Year State Type  Consumption
0              0  2021    10    4          1.0
1              1  2020    10    3          1.0
2              2  2021    11    3          1.0
3              3  2021    11    2          1.0
4              4  2020    11    4          1.0
...          ...   ...   ...  ...          ...
996          996  2021    10    3          5.0
997          997  2021    24    3          5.0
998          998  2021    40    1          5.0
999          999  2021    19    2          5.0
1000        1000  2019    11    1          5.0

[1001 rows x 5 columns]

In [18]:
X = data.iloc[:,:-1].values
X

array([[0, 2021, 10, 4],
       [1, 2020, 10, 3],
       [2, 2021, 11, 3],
       ...,
       [998, 2021, 40, 1],
       [999, 2021, 19, 2],
       [1000, 2019, 11, 1]], dtype=object)

In [19]:
Y =  data.iloc[:,4].values
Y

array([1., 1., 1., ..., 5., 5., 5.])

In [20]:
from sklearn.model_selection import train_test_split 
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.20)

In [21]:
#feature scaling
from sklearn.preprocessing import StandardScaler    
st_x= StandardScaler()
X_train = st_x.fit_transform(X_train)    
X_test = st_x.transform(X_test) 

In [22]:
from sklearn.neighbors import KNeighborsClassifier 

model = KNeighborsClassifier(n_neighbors=5)
model.fit(X_train, y_train)

KNeighborsClassifier()

In [23]:
answers = []
y_pred = model.predict(X_test)
for i in y_pred:
  if i==1:
    answers.append(11.5)
  if i==2:
    answers.append(21)
  if i==3:
    answers.append(37.6)
  if i==4:
    answers.append(52)
  if i==5:
    answers.append(64)
print(answers)

[64, 64, 11.5, 52, 21, 21, 11.5, 11.5, 21, 64, 11.5, 52, 21, 52, 11.5, 37.6, 64, 11.5, 11.5, 52, 11.5, 21, 64, 37.6, 37.6, 64, 37.6, 11.5, 37.6, 52, 11.5, 11.5, 64, 37.6, 64, 52, 64, 64, 52, 64, 64, 21, 52, 64, 52, 64, 37.6, 64, 64, 37.6, 37.6, 52, 21, 64, 52, 11.5, 11.5, 11.5, 37.6, 37.6, 37.6, 37.6, 11.5, 21, 21, 64, 64, 52, 21, 21, 64, 37.6, 52, 21, 64, 37.6, 52, 52, 11.5, 11.5, 37.6, 64, 52, 64, 11.5, 52, 52, 52, 21, 64, 11.5, 52, 21, 52, 64, 11.5, 37.6, 11.5, 21, 52, 37.6, 64, 11.5, 21, 37.6, 37.6, 37.6, 21, 21, 64, 37.6, 52, 52, 37.6, 37.6, 11.5, 52, 52, 64, 37.6, 11.5, 64, 64, 11.5, 21, 52, 52, 21, 64, 11.5, 37.6, 64, 11.5, 52, 21, 52, 11.5, 21, 64, 11.5, 11.5, 64, 37.6, 11.5, 37.6, 11.5, 37.6, 64, 21, 37.6, 37.6, 52, 21, 52, 37.6, 37.6, 64, 11.5, 11.5, 11.5, 64, 52, 21, 37.6, 37.6, 11.5, 21, 64, 64, 64, 52, 52, 11.5, 21, 21, 37.6, 37.6, 21, 11.5, 11.5, 21, 21, 64, 64, 52, 64, 64, 52, 52, 11.5, 21, 52, 11.5, 11.5, 21, 64, 64, 52, 37.6, 52, 64]


In [24]:
from sklearn.metrics import confusion_matrix,classification_report
print(classification_report(y_test,y_pred))
print()

              precision    recall  f1-score   support

         1.0       0.93      0.85      0.89        46
         2.0       0.64      0.72      0.68        29
         3.0       0.82      0.79      0.81        39
         4.0       0.80      0.87      0.84        38
         5.0       0.94      0.90      0.92        49

    accuracy                           0.84       201
   macro avg       0.82      0.83      0.82       201
weighted avg       0.84      0.84      0.84       201




In [25]:
print(confusion_matrix(y_test,y_pred))

[[39  7  0  0  0]
 [ 3 21  5  0  0]
 [ 0  5 31  3  0]
 [ 0  0  2 33  3]
 [ 0  0  0  5 44]]
